before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libicu-dev ruby1.9.1-dev rubygems gcc make
  - cp .jrubyrc ~/
language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode
